name: build_appimage

on: workflow_dispatch

jobs:

  build_appimage:
    name: build_appimage
    
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Build appimage
        run: |
          python3 tools/build_appimage.py --version=${{ github.ref_name }} --jsonfile=tools/linux_libs.json
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: BeeRef*.appimage
          retention-days: 5
